"""
build_clusters.py
Run FIFTH (after embed.py). Runs BERTopic on all posts,
saves clusters.json with labels generated by Groq.
"""
import numpy as np, pandas as pd, json, os, pickle
from bertopic import BERTopic
from umap import UMAP
from hdbscan import HDBSCAN
from sklearn.feature_extraction.text import CountVectorizer
from dotenv import load_dotenv

load_dotenv()

DATA_DIR = os.path.join(os.path.dirname(__file__), "../data")

# Load precomputed embeddings (saves re-running sentence-transformers)
emb  = np.load(f"{DATA_DIR}/embeddings.npy", allow_pickle=True)
meta = pd.read_parquet(f"{DATA_DIR}/search_meta.parquet")

print(f"Loaded {len(emb)} embeddings for BERTopic...")

# ── BERTopic pipeline ─────────────────────────────────────────────────────────
# UMAP: reduce to 15D for clustering (preserves more structure than 2D)
umap_model = UMAP(
    n_components=15,
    n_neighbors=15,
    min_dist=0.1,
    metric="cosine",
    random_state=42,
)
# HDBSCAN: density clustering, handles noise natively
hdbscan_model = HDBSCAN(
    min_cluster_size=15,
    metric="euclidean",
    prediction_data=True,
)
# CountVectorizer: stopword filtering so labels aren't "the to and of"
vectorizer = CountVectorizer(
    stop_words="english",
    max_features=5000,
    ngram_range=(1, 2),
)

topic_model = BERTopic(
    umap_model=umap_model,
    hdbscan_model=hdbscan_model,
    vectorizer_model=vectorizer,
    nr_topics=10,               # default; endpoint accepts override
    calculate_probabilities=False,
    verbose=True,
)

texts  = meta["title"].fillna("").tolist()
topics, _ = topic_model.fit_transform(texts, emb)

topic_info = topic_model.get_topic_info()
print(topic_info[["Topic","Count","Name"]].to_string(index=False))

# ── UMAP 2D for scatter visualization ────────────────────────────────────────
print("Generating 2D UMAP projection for scatter viz...")
umap_2d = UMAP(
    n_components=2,
    n_neighbors=15,
    min_dist=0.1,
    metric="cosine",
    random_state=42,
)
coords_2d = umap_2d.fit_transform(emb)

# ── Groq topic labels ─────────────────────────────────────────────────────────
def generate_label(topic_id: int, words: list[str]) -> str:
    """Use Groq to generate a human-readable 3-5 word label for a topic cluster."""
    import os
    groq_key = os.getenv("GROQ_API_KEY")
    if not groq_key:
        return " ".join(words[:3])
    try:
        from groq import Groq
        client = Groq(api_key=groq_key)
        r = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            max_tokens=50,
            temperature=0.3,
            messages=[{
                "role": "user",
                "content": (
                    f"These words define a political topic cluster from Reddit (2024 US election period): "
                    f"{words[:10]}. Give a 3-5 word human-readable label. "
                    f"Return ONLY the label, nothing else."
                )
            }]
        )
        return r.choices[0].message.content.strip()
    except Exception as e:
        print(f"  Groq label failed for topic {topic_id}: {e}")
        return " ".join(words[:3])

# Build result dict
results = {
    "topics": [],
    "points": [],
    "topic_info": [],
}

for _, row in topic_info.iterrows():
    tid = int(row["Topic"])
    if tid == -1:
        label = "Uncategorized / Noise"
        words = []
    else:
        raw_words = [w for w, _ in topic_model.get_topic(tid)]
        words     = raw_words[:10]
        label     = generate_label(tid, words)
        print(f"  Topic {tid:3d}: {label}")

    results["topics"].append({
        "id":    tid,
        "count": int(row["Count"]),
        "label": label,
        "words": words,
    })

# Per-post cluster assignments + 2D coords
for i, (tid, pt) in enumerate(zip(topics, coords_2d)):
    results["points"].append({
        "id":         meta.iloc[i]["id"],
        "title":      meta.iloc[i]["title"][:80],
        "subreddit":  meta.iloc[i]["subreddit"],
        "topic_id":   int(tid),
        "x":          float(pt[0]),
        "y":          float(pt[1]),
    })

# Save topic model itself for nr_topics override at query time
topic_model.save(f"{DATA_DIR}/bertopic_model", serialization="safetensors", save_ctfidf=True)

out_path = f"{DATA_DIR}/clusters.json"
with open(out_path, "w") as f:
    json.dump(results, f)

print(f"\n✓ Saved clusters.json → {out_path}")
print(f"  Topics   : {len([t for t in results['topics'] if t['id'] >= 0])}")
print(f"  Noise pts: {len([p for p in results['points'] if p['topic_id'] == -1])}")